import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { translations } from '../data/translations';
import {
  Sparkles,
  TrendingUp,
  Brain,
  Lightbulb,
  CheckCircle,
  Clock,
  ChevronDown
} from 'lucide-react';

export const Recommendations: React.FC = () => {
  const { language, recommendations } = useApp();
  const [filter, setFilter] = useState<'all' | 'high' | 'medium' | 'low'>('all');
  const t = translations[language] || translations.en;

  const filteredRecs = recommendations.filter(
    (rec) => filter === 'all' || rec.priority === filter
  );

  const getPriorityStyle = (priority: string) => {
    switch (priority) {
      case 'high':
        return {
          badge: 'bg-red-500/10 text-red-400 border border-red-500/20',
          border: 'border-red-500/20 hover:border-red-500/40 hover:shadow-red-500/5',
          bullet: 'bg-red-400'
        };
      case 'medium':
        return {
          badge: 'bg-violet-500/10 text-violet-400 border border-violet-500/20',
          border: 'border-violet-500/20 hover:border-violet-500/40 hover:shadow-violet-500/5',
          bullet: 'bg-violet-400'
        };
      case 'low':
        return {
          badge: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20',
          border: 'border-emerald-500/20 hover:border-emerald-500/40 hover:shadow-emerald-500/5',
          bullet: 'bg-emerald-400'
        };
      default:
        return {
          badge: 'bg-slate-500/10 text-slate-400 border border-slate-500/20',
          border: 'border-border/60 hover:border-primary/30',
          bullet: 'bg-slate-400'
        };
    }
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      
      {/* Header Description */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <h2 className="text-2xl font-extrabold tracking-tight">{t.recommendationsTitle}</h2>
          <p className="text-sm text-muted-foreground">
            Personalized lifestyle guidelines generated by game-theoretic explainability modeling of your active biometrics.
          </p>
        </div>
        
        {/* Category filter buttons */}
        <div className="flex items-center space-x-1.5 bg-secondary/35 border border-border/80 p-1.5 rounded-xl self-start sm:self-auto text-xs font-semibold">
          {(['all', 'high', 'medium', 'low'] as const).map((opt) => (
            <button
              key={opt}
              onClick={() => setFilter(opt)}
              className={`px-3 py-1.5 rounded-lg capitalize transition-colors ${
                filter === opt ? 'bg-primary text-white' : 'hover:bg-secondary text-muted-foreground hover:text-foreground'
              }`}
            >
              {opt}
            </button>
          ))}
        </div>
      </div>

      {/* Recommendations Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        
        {filteredRecs.length > 0 ? (
          filteredRecs.map((rec) => {
            const styles = getPriorityStyle(rec.priority);
            return (
              <div
                key={rec.id}
                className={`bg-card/45 backdrop-blur-md border rounded-3xl p-5 md:p-6 shadow-lg flex flex-col justify-between space-y-6 transition-all duration-300 ${styles.border}`}
              >
                <div className="space-y-4">
                  {/* Category row */}
                  <div className="flex items-center justify-between">
                    <span className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full ${styles.badge}`}>
                      {rec.priority} PRIORITY
                    </span>
                    
                    <span className="text-[10px] font-bold text-muted-foreground font-mono bg-secondary/40 border border-border/50 px-2 py-0.5 rounded-full">
                      Confidence: {rec.confidenceScore}%
                    </span>
                  </div>

                  {/* Title & description */}
                  <div className="space-y-1">
                    <h3 className="text-base font-bold text-foreground">{rec.title}</h3>
                    <p className="text-xs text-muted-foreground leading-relaxed">{rec.description}</p>
                  </div>

                  {/* Explanation Cause */}
                  <div className="p-3.5 bg-secondary/30 border border-border/40 rounded-2xl space-y-2">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-1.5">
                      <Brain size={12} className="text-indigo-400" /> Explainable ML Attribution
                    </p>
                    <p className="text-xs text-foreground/90 leading-relaxed font-sans">
                      {rec.reason}
                    </p>
                  </div>
                </div>

                {/* Impact row */}
                <div className="pt-4 border-t border-border/40 flex items-start space-x-2.5 text-xs text-indigo-400 font-semibold bg-primary/5 -mx-5 -mb-5 px-5 py-3 rounded-b-3xl">
                  <Lightbulb size={16} className="shrink-0 mt-0.5" />
                  <div>
                    <span className="text-[10px] text-muted-foreground font-bold uppercase tracking-wider block">Expected Impact</span>
                    <p className="text-xs mt-0.5 font-bold leading-normal">{rec.expectedImpact}</p>
                  </div>
                </div>
              </div>
            );
          })
        ) : (
          <div className="col-span-2 text-center py-20 text-muted-foreground text-xs">
            No recommendations match the active priority filter.
          </div>
        )}

      </div>

    </div>
  );
};
